using Celeste.Mod.Entities;
using Celeste.Mod.UI;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Mono.Cecil;
using Mono.Cecil.Cil;
using MonoMod;
using MonoMod.Cil;
using MonoMod.Utils;
using System;
using System.Linq;
using System.Reflection;
using System.Runtime.ExceptionServices;

namespace Monocle {
    class patch_Engine : Engine {

        public static new int ViewWidth { get; private set; }
        public static void SetViewWidth(int value) => ViewWidth = value;

        public static new int ViewHeight { get; private set; }
        public static void SetViewHeight(int value) => ViewHeight = value;

        public static new Viewport Viewport { get; private set; }
        public static void SetViewport(Viewport value) => Viewport = value;

#pragma warning disable CS0649 // variable defined in vanilla
        private Scene nextScene;
#pragma warning restore CS0649

        /// <summary>
        /// Allows to check which scene is next in methods like Entity.SceneEnd() or Scene.End().
        /// </summary>
        public static Scene NextScene => ((patch_Engine) Instance).nextScene;

        public patch_Engine(int width, int height, int windowWidth, int windowHeight, string windowTitle, bool fullscreen, bool vsync)
            : base(width, height, windowWidth, windowHeight, windowTitle, fullscreen, vsync) {
            // no-op. MonoMod ignores this - we only need this to make the compiler shut up.
        }

        private static readonly FieldInfo f_Game_RunApplication = typeof(Game).GetField("RunApplication", BindingFlags.NonPublic | BindingFlags.Instance);
        private static readonly FieldInfo f_Game_hasInitialized = typeof(Game).GetField("hasInitialized", BindingFlags.NonPublic | BindingFlags.Instance);
        private static readonly MethodInfo m_Game_RunLoop = typeof(Game).GetMethod("RunLoop", BindingFlags.NonPublic | BindingFlags.Instance);
        private static readonly MethodInfo m_Game_AfterLoop = typeof(Game).GetMethod("AfterLoop", BindingFlags.NonPublic | BindingFlags.Instance);
        
        // The cctor generated by the fields above cause the original one to be moved to a new method with this name
        [PatchEngineCctor]
        public static extern void orig_ctor_Engine();

        [MonoModReplace]
        public new void RunWithLogging() {
            bool continueLoop = false;
            restart:;
            try {
                if (!continueLoop)
                    Run();
                else {
                    m_Game_RunLoop.Invoke(this, Array.Empty<object>());
                    EndRun();
                    m_Game_AfterLoop.Invoke(this, Array.Empty<object>());
                }
            } catch (Exception ex) {
                if (continueLoop && ex is TargetInvocationException)
                    // TargetInvocationException always has a non-null InnerException
                    ex = ex.InnerException!;

                // Try to handle the error by opening an in-game handler first (unless the exception occurred while exiting)
                // also, make sure the game has initialized, else the crash handler will... crash. (how ironic)
                bool isExiting = !(bool) f_Game_RunApplication.GetValue(this)!;
                bool hasInitialized = (bool) f_Game_hasInitialized.GetValue(this)!;

                if (!isExiting && hasInitialized) {
                    ExceptionDispatchInfo dispatch = CriticalErrorHandler.HandleCriticalError(ExceptionDispatchInfo.Capture(ex));
                    if (dispatch == null)  {
                        // Restart the update loop
                        try {
                            Monocle.Draw.SpriteBatch.End(); // This prevents hard crash cascades
                        } catch {}

                        (Scene as patch_Scene)?.ClearOnEndOfFrame();

                        continueLoop = true;
                        goto restart;
                    }

                    // The exception handling failed
                    ex = dispatch.SourceException;
                }

                // Lazy loading can cause some issues, f.e. vanishing outlines on dust bunnies.
                // It thus shouldn't be enabled automatically.
                /*
                if (e is OutOfMemoryException && CoreModule.Instance?._Settings != null && !CoreModule.Settings.LazyLoading) {
                    CoreModule.Settings.LazyLoading = true;
                    CoreModule.Instance.SaveSettings();
                }
                */

                ErrorLog.Write(ex);
                ErrorLog.Open();
            }
        }

        [MonoModIgnore]
        [PatchEngineUpdate]
        protected override extern void Update(GameTime gameTime);

        /// <summary>
        /// A game speed factor set by various entities, such as <see cref="Celeste.Seeker"/> or <see cref="Celeste.AngryOshiro"/>.<br/>
        /// This field should not be modified by mods. Use a <see cref="TimeRateModifier"/> component instead.
        /// </summary>
        /// <remarks>
        /// This field is used by entities which don't appear in vanilla together, or more than once in the same room.
        /// As such, if two of them try to modify the time rate, they will overwrite each other's values.
        /// </remarks>
        /// <seealso cref="EffectiveTimeRate"/>
        [Obsolete(
            "This field should be reserved to vanilla entities which modify time. "
            + "Use a TimeRateModifier component instead to prevent conflicts.")]
        public static new float TimeRate;

        /// <summary>
        /// The Assist/Variant Mode "Game Speed" factor by which <see cref="Engine.RawDeltaTime"/> is multiplied.<br/>
        /// This field should not be modified by mods. Use a <see cref="TimeRateModifier"/> component instead.
        /// </summary>
        /// <seealso cref="EffectiveTimeRate"/>
        [Obsolete(
            "This field should be reserved to the Assist/Variant Mode \"Game Speed\" modifier. "
            + "Use a TimeRateModifier component instead to prevent conflicts.")]
        public static new float TimeRateB;

        /// <summary>
        /// The final time rate factor applied to <see cref="Engine.RawDeltaTime"/> before being set to
        /// <see cref="Engine.DeltaTime"/>.<br />
        /// This value is calculated <b>at the beginning of the frame</b> by multiplying
        /// <see cref="TimeRate"/>, <see cref="TimeRateB"/>, and the <see cref="TimeRateModifier.Multiplier"/>s
        /// of all enabled <see cref="TimeRateModifier"/>s in the scene together.
        /// </summary>
        public static float EffectiveTimeRate;

        /// <summary>
        /// Aggregates the <see cref="TimeRateModifier.Multiplier"/>s of all enabled <see cref="TimeRateModifier"/>s in the scene
        /// by multiplying them together.
        /// </summary>
        private static float GetTimeRateComponentMultiplier(Scene scene) {
            return scene?.Tracker.GetComponents<TimeRateModifier>()
                                 .Cast<TimeRateModifier>()
                                 .Where(trm => trm.Enabled)
                                 .Select(trm => trm.Multiplier)
                                 .Aggregate(1f, (acc, val) => acc * val)
                   ?? 1;
        }

    }
    public static class EngineExt {

        public static int ViewWidth {
            get {
                return Engine.ViewWidth;
            }
            set {
                patch_Engine.SetViewWidth(value);
            }
        }

        public static int ViewHeight {
            get {
                return Engine.ViewHeight;
            }
            set {
                patch_Engine.SetViewHeight(value);
            }
        }

        public static Viewport Viewport {
            get {
                return Engine.Viewport;
            }
            set {
                patch_Engine.SetViewport(value);
            }
        }

    }
}

namespace MonoMod {
    
    /// <summary>
    /// Patch the method to apply TimeRateModifier multipliers.
    /// </summary>
    [MonoModCustomMethodAttribute(nameof(MonoModRules.PatchEngineUpdate))]
    class PatchEngineUpdateAttribute : Attribute { }
    
    /// <summary>
    /// Patch the method to swap "Framework" for "Core"
    /// </summary>
    [MonoModCustomMethodAttribute(nameof(MonoModRules.PatchEngineCctor))]
    class PatchEngineCctorAttribute : Attribute { }
    
    static partial class MonoModRules {
        public static void PatchEngineUpdate(ILContext context, CustomAttribute attrib) {
            TypeDefinition t_Engine = context.Method.DeclaringType;
            FieldReference f_scene = t_Engine.FindField("scene");
            FieldReference sf_TimeRate = t_Engine.FindField("TimeRate");
            FieldReference sf_TimeRateB = t_Engine.FindField("TimeRateB");
            FieldReference sf_EffectiveTimeRate = t_Engine.FindField("EffectiveTimeRate");
            MethodReference m_GetTimeRateComponentMultiplier = t_Engine.FindMethod("GetTimeRateComponentMultiplier");
            VariableDefinition v_componentTimeRate = new(context.Import(typeof(float)));
            context.Method.Body.Variables.Add(v_componentTimeRate);

            ILCursor cursor = new ILCursor(context);
            cursor.GotoNext(
                instr => instr.MatchCall("Monocle.Engine", "System.Single get_RawDeltaTime()"),
                instr => instr.MatchLdsfld("Monocle.Engine", "TimeRate"),
                instr => instr.MatchMul());
            // float componentTimeRate = GetTimeRateMultiplier(this.Scene);
            cursor.EmitLdarg0();
            cursor.EmitLdfld(f_scene);
            cursor.EmitCall(m_GetTimeRateComponentMultiplier);
            cursor.EmitStloc(v_componentTimeRate);

            // EffectiveTimeRate = TimeRate * TimeRateB * componentTimeRate
            cursor.EmitLdsfld(sf_TimeRate);
            cursor.EmitLdsfld(sf_TimeRateB);
            cursor.EmitMul();
            cursor.EmitLdloc(v_componentTimeRate);
            cursor.EmitMul();
            cursor.EmitStsfld(sf_EffectiveTimeRate);

            // multiply time rate with GetTimeRateComponentMultiplier(scene) stored in componentTimeRate
            cursor.GotoNext(MoveType.After,
                instr => instr.MatchLdsfld("Monocle.Engine", "TimeRateB"),
                instr => instr.MatchMul());
            cursor.EmitLdloc(v_componentTimeRate);
            cursor.EmitMul();
        }
        
        public static void PatchEngineCctor(ILContext context, CustomAttribute attrib) {
            ILCursor cursor = new ILCursor(context);
            
            // This only exists in 1.4.1.0 and later
            if (CurrentGameVersion >= new Version(1, 4, 1, 0)) {
                cursor.GotoNext(instr => instr.MatchLdstr(".NET Framework "));
                cursor.Next!.Operand = ".NET Core ";
            }
        }
    }
}
