name: TAS Sync Check

on:
  pull_request:
    branches: [dev]

jobs:
  check:
    strategy:
      matrix:
        tas:
          - name: Celeste 100%
            url: "https://github.com/VampireFlower/CelesteTAS/archive/d34bd24434888ea15ef36d91522a803749cda96d.zip"
            path: "CelesteTAS-d34bd24434888ea15ef36d91522a803749cda96d/0 - 100%.tas"

          - name: Strawberry Jam All Levels
            url: "https://github.com/VampireFlower/StrawberryJamTAS/archive/9e019be8c48d2784089315eede0201ed058f82a4.zip"
            path: "StrawberryJamTAS-9e019be8c48d2784089315eede0201ed058f82a4/0-SJ All Levels.tas"
            bundle: "https://celestemodupdater.0x0a.de/pinned-mods/StrawberryJam2021-Bundle-8b6d87e2.zip"

    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: ${{ matrix.tas.name }}

    steps:
    - uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Wait for Azure build on commit ${{ github.sha }}
      run: cd .github/tas-check && ./1-get-build-url.sh "${{ github.sha }}"

    - name: Install Everest and required mods
      run: cd .github/tas-check && ./2-1-install.sh "${{ matrix.tas.url }}" "${{ matrix.tas.bundle }}"

    - name: Run TAS at ${{ matrix.tas.path }}
      run: cd .github/tas-check && ./3-run.sh "${{ matrix.tas.path }}"
