name: TAS Sync Check

on:
  pull_request:
    branches: [dev]

jobs:
  check:
    strategy:
      matrix:
        tas:
          - name: Celeste 100%
            url: "https://github.com/VampireFlower/CelesteTAS/archive/57aa973164cb5924ba9114923869c7c3b0291549.zip"
            path: "CelesteTAS-57aa973164cb5924ba9114923869c7c3b0291549/0 - 100%.tas"

          - name: Strawberry Jam All Levels
            url: "https://github.com/VampireFlower/StrawberryJamTAS/archive/5c3e1a904af8bb0e37fe88e084a0fbf7241eee0b.zip"
            path: "StrawberryJamTAS-5c3e1a904af8bb0e37fe88e084a0fbf7241eee0b/0-SJ All Levels.tas"
            bundle: "https://celestemodupdater.0x0a.de/pinned-mods/StrawberryJam2021-Bundle-36e2909e.zip"

    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: ${{ matrix.tas.name }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Wait for Azure build on commit ${{ github.sha }}
      run: cd .github/tas-check && ./1-get-build-url.sh "${{ github.sha }}"

    - name: Install Everest and required mods
      run: cd .github/tas-check && ./2-1-install.sh "${{ matrix.tas.url }}" "${{ matrix.tas.bundle }}"

    - name: Run TAS at ${{ matrix.tas.path }}
      run: cd .github/tas-check && ./3-run.sh "${{ matrix.tas.path }}"
