name: TAS Sync Check

on:
  pull_request:
    branches: [dev]

jobs:
  check:
    strategy:
      matrix:
        tas:
          - name: Celeste 100%
            url: "https://github.com/VampireFlower/CelesteTAS/archive/6c72a299ea010a97cb5fa13fc48ed4e60f747c71.zip"
            path: "CelesteTAS-6c72a299ea010a97cb5fa13fc48ed4e60f747c71/0 - 100%.tas"

          - name: Strawberry Jam All Levels
            url: "https://github.com/VampireFlower/StrawberryJamTAS/archive/56cbf981faa82610cd1f0d67a2d5a45d08d6f7e5.zip"
            path: "StrawberryJamTAS-56cbf981faa82610cd1f0d67a2d5a45d08d6f7e5/0-SJ All Levels.tas"
            bundle: "https://celestemodupdater.0x0a.de/pinned-mods/StrawberryJam2021-Bundle-926d1dcf.zip"

    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: ${{ matrix.tas.name }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Wait for Azure build on commit ${{ github.sha }}
      run: cd .github/tas-check && ./1-get-build-url.sh "${{ github.sha }}"

    - name: Install Everest and required mods
      run: cd .github/tas-check && ./2-1-install.sh "${{ matrix.tas.url }}" "${{ matrix.tas.bundle }}"

    - name: Run TAS at ${{ matrix.tas.path }}
      run: cd .github/tas-check && ./3-run.sh "${{ matrix.tas.path }}"
